name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: eranrund/gha-test-app
        submodules: 'recursive'

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          **Hello** ${{ secrets.GITHUB_TOKEN }}
          🌏
          !
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default
