name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check that test-app still builds
      uses: ./.github/actions/check-dependant-rust-repo
      with:
        remoteRepo: eranrund/gha-test-app
        id: test-app
