name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latesto

    steps:
    - name: Dump context
      uses: crazy-max/ghaction-dump-context@v1


    - uses: actions/checkout@v3
      with:
        repository: eranrund/gha-test-app
        submodules: 'recursive'

    - name: Build
      run: |
        cd gha-test-lib
        #git remote set-url origin ${{ github.repositoryUrl }} - this is git:// and GHA doesn't seem to like it
        git remote set-url origin https://github.com/${{ github.repository }}
        git fetch origin ${{ github.ref }}:gha-test
        git checkout gha-test
        cd ..

        cargo build --verbose || echo "UPREV_FAILED=1" >> "$GITHUB_ENV"

    - name: Build with the 

    - name: Comment on PR
      uses: mshick/add-pr-comment@v1
      if: env.UPREV_FAILED == '1'
      with:
        message: |
          Heads up, I tried building XXX using this branch and it failed.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default
