name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: eranrund/gha-test-app
        submodules: 'recursive'

    - name: Build
      run: |
        cd gha-test-lib
        #git remote set-url origin ${{ github.repositoryUrl }} - this is git:// and GHA doesn't seem to like it
        git remote set-url origin https://github.com/${{ github.repository }}
        git fetch origin ${{ github.ref }}:gha-test
        git checkout gha-test
        cd ..

        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          **Hello**
          🌏
          !
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default
